// variety.js — variety as a pipeline property, not as Max's memory.
//
// Locked decision 6: with no theme, the pipeline picks underused relationship
// territory for itself before Pair Author runs. The important part of the
// spec's phrasing is that the brief is POSITIVE — it asks for what is
// underused rather than showing old boards and saying "be different", which
// tends to produce work that is merely different rather than work that is new.
//
// Since 2026-08-04 (design.md D-3) the brief steers on two axes:
//
//   family — library coverage over time. Counted at family grain (10 buckets
//            stay meaningful at 20 boards); the brief names specific SHAPES
//            inside the least-used families, each a precise ask with a
//            paradigm pair behind it.
//   stance — board composition. Every brief carries quotas drawn from the
//            portable stances, because a board wants four different kinds of
//            question regardless of where its words came from.
//
// Counts are recomputed on demand rather than stored. Thirty runs is nothing
// to walk, and a stored count is a second source of truth that can drift from
// the runs it claims to summarise.

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

import {
  PORTABLE_STANCES,
  SHAPES,
  SHIPPED_LABELS,
  STANCES,
  isNameable,
  resolveShape,
  stanceOf,
} from './corpus/vocabulary.js';

export { SHAPES } from './corpus/vocabulary.js';

const PUZZLES_DIR = fileURLToPath(new URL('../puzzles/', import.meta.url));

const REQUEST_COUNT = 3;
const AVOID_COUNT = 2;
// How many of the newest published boards feed the word-repetition avoid list
// (D-19). "Too soon", not "ever again": five boards is roughly a week of play.
const RECENT_PUBLISHED_BOARDS = 5;
const QUOTA_STANCES = 4;

/** The words of a set, lower-cased, for joining a board back to its pairs. */
const wordsOf = (set) => set.pairs.flat().map((word) => word.trim().toLowerCase());

/**
 * Walks the shipped boards and every run, counting how often each shape — and
 * through it each family and stance — has been used, remembering which shapes
 * were used most recently.
 *
 * A set whose shape cannot be determined counts as `unknown` — the board
 * builder may have altered words after the pair author declared them, and a
 * missed join must never block brief construction. Legacy shape ids from the
 * retired 13-shape list resolve through the vocabulary's aliases, so history
 * stays countable.
 */
export function buildRelationshipIndex({ store, puzzlesDir = PUZZLES_DIR } = {}) {
  const counts = {};
  const familyCounts = {};
  const stanceCounts = {};
  const recent = [];
  const hardestSources = [];
  const hardestStances = [];
  let unknown = 0;

  const record = (declared) => {
    const shape = resolveShape(declared);
    if (shape) {
      counts[shape.id] = (counts[shape.id] ?? 0) + 1;
      familyCounts[shape.family] = (familyCounts[shape.family] ?? 0) + 1;
      stanceCounts[shape.stance] = (stanceCounts[shape.stance] ?? 0) + 1;
      recent.push(shape.id);
    } else {
      unknown += 1;
    }
  };

  // Hand-authored boards: hand-labelled, since they predate the `shape` field.
  //
  // A board with NO label entry is skipped, not counted as unknown. Since
  // 2026-08-05 puzzles/ also holds published pipeline boards, and those are
  // already counted below through their run — joined from the pair author's
  // declarations, which is the reliable path and the one that knows about
  // aliases. Counting them here would add four to `unknown` per published
  // board and steadily tell every future brief that the corpus is unreadable.
  //
  // A labelled board with an unlabelled SET still records unknown: that is a
  // real gap in the hand-labelling, and the tally is where it should show.
  if (existsSync(puzzlesDir)) {
    for (const file of readdirSync(puzzlesDir).filter((name) => name.endsWith('.json')).sort()) {
      let board;
      try {
        board = JSON.parse(readFileSync(join(puzzlesDir, file), 'utf8'));
      } catch {
        continue;
      }
      const labels = SHIPPED_LABELS[board.id];
      if (!labels) continue;
      for (const set of board.sets ?? []) record(labels[set.id]);
    }
  }

  // Runs: joined from the board back to the pair author's declared shapes.
  //
  // Mock runs are skipped. A fixture run replays the same board every time, so
  // counting it would tell the brief that its shapes are heavily used and steer
  // real runs away from them — variety pressure generated by a board nobody
  // authored. run-store already records `brief.mock` for exactly this reason
  // ("a mock-derived board is never mistaken for real editorial signal"); this
  // is the second place that has to honour it. One had been sitting in the
  // corpus since 2026-08-03, marked approved.
  const publishedBoards = [];
  for (const runId of store?.listRuns() ?? []) {
    if (isMockRun(store, runId)) continue;
    for (const { board, shapeByWord, grades } of attemptsOf(store, runId)) {
      const shapeOf = (set) => {
        const shapes = wordsOf(set).map((word) => shapeByWord.get(word)).filter(Boolean);
        return shapes.length > 0 ? mostCommon(shapes) : null;
      };
      for (const set of board.sets ?? []) record(shapeOf(set));
      recordHardest(board, shapeOf, grades);
    }
    // Publish events, for the word-repetition avoid list (D-19): the words of
    // a PUBLISHED board reached a player, so a soon-repeated one reads as
    // retreading. Rejected boards never shipped; their words stay free.
    collectPublishedWords(store, runId, publishedBoards);
  }

  // Newest publishes first, bounded — the complaint is "too soon", not "ever
  // again", so only the freshest boards' words go on the avoid list.
  const recentPublishedWords = [];
  const seenWords = new Set();
  publishedBoards.sort((a, b) => (a.at < b.at ? 1 : -1));
  for (const { words } of publishedBoards.slice(0, RECENT_PUBLISHED_BOARDS)) {
    for (const word of words) {
      const key = word.toLowerCase();
      if (seenWords.has(key)) continue;
      seenWords.add(key);
      recentPublishedWords.push(word);
    }
  }

  return {
    counts,
    familyCounts,
    stanceCounts,
    recent,
    unknown,
    recentPublishedWords,
    shapes: SHAPES,
    // How the HARDEST set of each board earned its difficulty, newest last
    // (design.md D-8). Not a count of shapes — a count of the two ways a board
    // can be made hard, which is the thing that had quietly become one.
    hardestSources,
    // What KIND of question each board's hardest set asked, newest last
    // (design.md D-13). The sibling axis: D-8 stopped every Black being a rare
    // word, and the space it opened filled up with clocks.
    hardestStances,
  };

  /**
   * Records how this board's Black earned its difficulty — two axes.
   *
   * `hardestSources` is D-8's axis: arrangement or vocabulary. It prefers 03's
   * own `difficultySource`, a judgement made while grading, and falls back to
   * the shape for the thirty-odd boards graded before that field existed (the
   * three nameable shapes are the ones whose only lever for extra difficulty is
   * a rarer word).
   *
   * `hardestStances` is D-13's axis, and it exists because fixing D-8's rut
   * grew another one inside it. "Arrangement-hard" is a broad answer; a TIME
   * SPAN is the easiest arrangement-hard set to author, so the builder kept
   * reaching for one. Measured across 57 boards: 19 of 57 Blacks were a time
   * set — a third of the hardest slot spent on one stance. The stance is always
   * read from the shape, never from 03, because `difficultySource` says how a
   * set is hard and this asks what KIND of question it is.
   */
  function recordHardest(board, shapeOf, grades) {
    const sets = board.sets ?? [];
    if (sets.length === 0) return;
    const hardest = sets.reduce((a, b) => (b.difficulty > a.difficulty ? b : a));
    const shape = shapeOf(hardest);

    // Recorded first and independently: a board can have a declared source and
    // an unjoinable shape, or the reverse, and neither axis should lose a
    // datapoint because the other one is missing.
    const stance = shape ? stanceOf(shape) : null;
    if (stance) hardestStances.push(stance);

    const declared = grades?.get(hardest.id)?.difficultySource;
    if (declared === 'arrangement' || declared === 'vocabulary' || declared === 'both') {
      hardestSources.push(declared);
      return;
    }
    if (!shape) return; // unjoinable — guessing here would be worse than silence
    hardestSources.push(isNameable(shape) ? 'vocabulary' : 'arrangement');
  }
}

/** The words of each publish event's board, with its timestamp. Degrades quiet. */
function collectPublishedWords(store, runId, out) {
  let decisions;
  try {
    decisions = store.readDecisions(runId);
  } catch {
    return;
  }
  for (const decision of decisions) {
    if (decision.type !== 'publish') continue;
    try {
      const board = store.readAttemptArtifact(runId, decision.attemptId, 'board.json');
      // Original casing, for the prompt — wordsOf lowercases for joining.
      const words = (board.sets ?? []).flatMap((set) => (set.pairs ?? []).flat());
      if (words.length > 0) out.push({ at: decision.at ?? '', words });
    } catch {
      // The attempt's board is unreadable — the avoid list just gets less data.
    }
  }
}

// An unreadable manifest is treated as real, not as mock: the failure mode of
// guessing wrong here is one board's shapes counted twice, which is far cheaper
// than silently dropping real runs out of the index.
function isMockRun(store, runId) {
  try {
    return store.readManifest(runId).brief?.mock === true;
  } catch {
    return false;
  }
}

function* attemptsOf(store, runId) {
  let attemptIds;
  try {
    attemptIds = store.listAttempts(runId);
  } catch {
    return;
  }
  for (const attemptId of attemptIds) {
    let board;
    try {
      board = store.readAttemptArtifact(runId, attemptId, 'board.json');
    } catch {
      continue; // no board: a run still working, or one that failed
    }
    // 03's grades, for `difficultySource`. Absent on every run before
    // 2026-08-05 and on revisions that reuse a parent stage, which is why the
    // caller has a shape-based fallback.
    let grades;
    try {
      const rated = store.readStageArtifact(runId, attemptId, '03-difficulty-rater', 'output.json');
      grades = new Map((rated.grades ?? []).map((grade) => [grade.setId, grade]));
    } catch {
      grades = new Map();
    }

    const shapeByWord = new Map();
    try {
      const authored = store.readStageArtifact(runId, attemptId, '01-pair-author', 'output.json');
      for (const pair of authored.pairs ?? []) {
        for (const word of [pair.a, pair.b]) {
          if (typeof word === 'string') shapeByWord.set(word.trim().toLowerCase(), pair.shape);
        }
      }
    } catch {
      // A revision reuses the parent's pair author, so its own folder has no
      // output. The board still counts; its shapes just land as unknown.
    }
    yield { board, shapeByWord, grades };
  }
}

const mostCommon = (values) => {
  const tally = new Map();
  for (const value of values) tally.set(value, (tally.get(value) ?? 0) + 1);
  return [...tally.entries()].sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))[0][0];
};

/**
 * The stance quotas every brief carries: the four least-used portable stances.
 * Portable only — `reference` reaches one family and `dimension` three, so
 * putting either in a quota would make specific families mandatory. They still
 * count toward the composition when an author reaches for them unprompted.
 *
 * Deterministic — ties break on name — like everything else in the brief.
 */
export function buildStanceQuotas({ index } = {}) {
  const stanceCounts = index?.stanceCounts ?? {};
  return [...PORTABLE_STANCES]
    .map((stance) => ({ stance, used: stanceCounts[stance] ?? 0 }))
    .sort((a, b) => a.used - b.used || (a.stance < b.stance ? -1 : 1))
    .slice(0, QUOTA_STANCES)
    .map((entry) => entry.stance);
}

/**
 * Turns the index into a brief for Pair Author.
 *
 * Family is the coverage axis: the brief finds the least-used families and
 * names the least-used shapes INSIDE them — a precise ask (each shape has a
 * paradigm pair in the prompt) rather than a category the model can satisfy
 * from its rut. Stance quotas ride on every brief.
 *
 * Deterministic — ties break on name — so the same library always produces the
 * same brief, and a run's conditions can be reconstructed later.
 */
export function buildVarietyBrief({ index, count = 8 } = {}) {
  const counts = index?.counts ?? {};
  const familyCounts = index?.familyCounts ?? {};

  // Least-used families first; inside a family, least-used shapes first.
  const ranked = [...SHAPES].sort(
    (a, b) =>
      (familyCounts[a.family] ?? 0) - (familyCounts[b.family] ?? 0) ||
      a.family - b.family ||
      (counts[a.id] ?? 0) - (counts[b.id] ?? 0) ||
      (a.id < b.id ? -1 : 1),
  );

  // One shape per family across the least-used families, so the request
  // spreads rather than triple-dipping the single emptiest bucket.
  const relationshipShapes = [];
  const familiesTaken = new Set();
  for (const shape of ranked) {
    if (relationshipShapes.length >= REQUEST_COUNT) break;
    if (familiesTaken.has(shape.family)) continue;
    familiesTaken.add(shape.family);
    relationshipShapes.push(shape.id);
  }

  // Recently used AND actually over-represented: avoiding a shape used once is
  // just noise in the prompt.
  const requested = new Set(relationshipShapes);
  const recent = [...new Set([...(index?.recent ?? [])].reverse())];
  const avoidShapes = recent
    .filter((shape) => !requested.has(shape) && (counts[shape] ?? 0) > 1)
    .slice(0, AVOID_COUNT);

  return {
    count,
    relationshipShapes,
    avoidShapes,
    // The word-repetition avoid list (D-19): a soft steer, not a check — the
    // review card is where a repeat that slips through gets caught.
    avoidWords: index?.recentPublishedWords ?? [],
    stanceQuotas: buildStanceQuotas({ index }),
    ...leanAgainstRecentDifficulty(index),
    ...askForHardestSlot(index),
  };
}

/**
 * The brief fields that MARK a run as surprise-me, and so the only fields a
 * themed brief drops.
 *
 * `relationshipShapes` is what tells the rest of the Studio a run had no
 * subject of its own — `api.js` reads it back to classify a run, and a themed
 * run's steer is its theme rather than a shape list. `avoidShapes` is its
 * negative half and travels with it.
 *
 * Everything else is about ruts ACROSS boards rather than about subject
 * matter, so it applies to every run whatever its theme.
 */
export const SURPRISE_ME_ONLY = Object.freeze(['relationshipShapes', 'avoidShapes']);

/**
 * The brief a THEMED run carries — the variety brief minus its surprise-me
 * markers.
 *
 * Derived by subtraction, deliberately, and this is the whole point of the
 * function. It used to be re-listed by hand at each caller, so D-13's
 * `varyHardestStance` reached surprise-me runs and silently missed every themed
 * one — including every board Max was complaining about when he asked for the
 * steer. Two callers each re-deriving "what does a brief carry" is a rule at
 * one door, which is this repo's recurring scar; a new steer added to
 * `buildVarietyBrief` now reaches themed runs by construction, and the only
 * thing anyone has to remember is whether it belongs on the exclusion list
 * above.
 */
export function buildThemedBrief({ index, count = 8 } = {}) {
  const brief = buildVarietyBrief({ index, count });
  for (const key of SURPRISE_ME_ONLY) delete brief[key];
  return brief;
}

/**
 * How many boards in a row have reached their hardest set the same way.
 *
 * The recent window only — this is about a rut, not about lifetime balance, and
 * Max's instruction was that either kind may top a board: *"they can both be
 * black, depending on the puzzle. I don't want to fall into a repetitive hole
 * where only one type of puzzle is one difficulty."* So it fires on a RUN of
 * sameness and says nothing otherwise.
 */
const RUT_LENGTH = 3;

/**
 * How many recent boards the STANCE rut looks at, and the share that trips it.
 *
 * Deliberately not `RUT_LENGTH`, and the reason is arity. D-8's axis has two
 * values — arrangement or vocabulary — so "the last three are identical" is a
 * strong, common signal there. Stance has EIGHT values, and the same rule
 * transplanted fires on 5 of 52 windows of real history: it did not fire on the
 * evening Max complained (his last three Blacks were time, dimension,
 * possession) even though 19 of the previous 54 had been time. A rule that
 * misses the complaint that motivated it is the wrong rule.
 *
 * Simulated against the whole corpus, a window of 8 at half share is the clean
 * discriminator: it fires on 16 of 47 windows and **every one of them is
 * `time`** — no false positive on any other stance in the project's history —
 * and eight boards is about the span of work over which Max noticed it.
 */
const HARDEST_WINDOW = 8;
const HARDEST_SHARE = 0.5;

/** How many underused stances the hardest-slot ask names. */
const ASK_COUNT = 3;

/**
 * The hardest-slot ask (design.md D-13, second amendment): POSITIVE and
 * ALWAYS ON.
 *
 * Its predecessor (`varyHardestStance`) named one stance to avoid and fired
 * only on a rut — the one negative lever in a file whose founding rule is
 * that the brief asks for what is underused rather than saying "be
 * different". The 2026-08-08 evening batch measured what a negative buys:
 * told to avoid `dimension`, five of six boards topped out on a `time` span,
 * three builders citing the steer as their reason, and the sixth escaped only
 * through a rare word — D-8's original rut. An exclusion can only relocate
 * the slot, because among arrangement-hard sets a span is always the easiest
 * thing to author next. Max's instruction, from his own review of that batch:
 * "All puzzles should pull from all taxonomies."
 *
 * So the ask names the 2–3 stances LEAST used in the hardest slot — ranked in
 * the recent window, ties broken by all-time count and then by name, so the
 * same library always produces the same brief. All eight stances are
 * candidates: this is a nudge for one slot, not a quota, so the portable-five
 * restriction that governs `stanceQuotas` does not apply. The rutted stance
 * can never be asked for, because it is by definition the most used.
 *
 * `hardestStanceLean` still names the rut when one exists (the old window and
 * share, kept with their calibration) — the renderers use it to say WHY the
 * ask matters — but the ask itself rides on every brief. Anti-monoculture,
 * never anti-anything: Max approved five span Blacks the same evening he
 * asked for this, and D-8's law stands — no stance is banned, no tier is
 * reserved.
 */
function askForHardestSlot(index) {
  const stances = index?.hardestStances ?? [];
  const window = stances.slice(-HARDEST_WINDOW);

  const windowCounts = new Map();
  for (const stance of window) windowCounts.set(stance, (windowCounts.get(stance) ?? 0) + 1);
  const allTimeCounts = new Map();
  for (const stance of stances) allTimeCounts.set(stance, (allTimeCounts.get(stance) ?? 0) + 1);

  const hardestStanceAsk = STANCES.map((stance) => stance.id)
    .sort(
      (a, b) =>
        (windowCounts.get(a) ?? 0) - (windowCounts.get(b) ?? 0) ||
        (allTimeCounts.get(a) ?? 0) - (allTimeCounts.get(b) ?? 0) ||
        (a < b ? -1 : 1),
    )
    .slice(0, ASK_COUNT);

  const lean =
    window.length >= HARDEST_WINDOW
      ? [...windowCounts.entries()].sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))[0]
      : null;
  const hasLean = lean !== null && lean[1] / HARDEST_WINDOW >= HARDEST_SHARE;

  return { hardestStanceAsk, ...(hasLean ? { hardestStanceLean: lean[0] } : {}) };
}

function leanAgainstRecentDifficulty(index) {
  const sources = index?.hardestSources ?? [];
  if (sources.length < RUT_LENGTH) return {};

  const window = sources.slice(-RUT_LENGTH);
  const [first] = window;
  // `both` is already varied — a rut is one PURE kind repeated.
  if (first === 'both' || !window.every((source) => source === first)) return {};

  return { varyHardestFrom: first };
}
